version: '3'

services:
  db:
    image: scylladb/scylla:4.5.4
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ./scylla.yaml:/etc/scylla/scylla.yaml
      - db-data:/var/lib/scylla

volumes:
  db-data: